version: "3.3"

services:
  db:
    image: postgis/postgis
    volumes:
      - ./dados:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mapas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mapas:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  dados: {}
  mapas: {}